#  Assignment 5

This assignment covers material on matrices, norms, condition numbers and eigensystems. The assignment is due by 5pm on Friday the 17th of April.

The breakdown of the marks is as follows:

Question 0 - [1 mark]  
Question 1 - [7 marks]  
Questino 2 - [6 marks]  
Question 3 - [7 marks]  
Question 4 - [9 marks]  

# Question 0

You should have saved this notebook to your ACM20030-Assignments folder. Now:
- commit the notebook to your local repository
- push the changes to the GitHub

In [31]:
import numpy as np
from numpy import linalg as la
np.set_printoptions(linewidth=200)  # This stops line wrapping of larger matrices

# Question 1 - practice manipulating arrays

This questions asks you write a few functions for manipulating arrays of data

## Q1 a

Write a function that checks if a given $n\times n$ matrix is symmetric. Use only loops and `.shape` function from numpy (do not use any other special numpy functions).

In [32]:
def symmetrytest(A):
    n = A.shape[0] #returns current shape of a numpy array. 
#     print(n)
    if(A.shape[1]!= n):
        return 0
    for i in range(0, n):
        for j in range(i + 1, n): #Checks every number below the diagonal
            if(A[i][j] != A[j][i]): #if not equal not symmetirc
                return 0 
    return 1

Test your function on the two matrices below

In [33]:
A = np.random.rand(5, 5)
SymMatrix = (A + A.T)/2

In [34]:
# prints to test function
# print(A)
# print(SymMatrix)
# print(A.shape[1])

In [35]:
#if symmetric 1 will be returned if not a 0 is returned. 

symmetrytest(A)

0

In [36]:
symmetrytest(SymMatrix)

1

## Q1 b

Write a function to transpose a general $n\times n$ matrix. Do this by writing loops and not using any special functions like `np.transpose()`, `A.T`, or any functions from any other library.

In [37]:
def transpose(A):
    n = A.shape[0] #shape of Matrix A 
    B = np.empty([n, n]) #Return a new array of given shape and type, without initializing entries
    for i in range(0, n):
        for j in range(0, n): #for all values swaps them diagonally thus transpose is obtained. 
            B[i][j] = A[j][i]
    return B

Check your code by transposing the below random matrix and checking that $A^T \neq A$ and $(A^T)^T - A = 0$

In [38]:
A = np.random.rand(6, 6)

In [39]:
print(A)

print("Transposed matrix,", transpose(A))

print("Thus the matricies are not equal.")

[[0.80261215 0.95291481 0.06618431 0.00711457 0.04169387 0.02797157]
 [0.98627718 0.35064656 0.96643981 0.52098375 0.25743676 0.11908936]
 [0.94468356 0.6652367  0.08343675 0.87144822 0.27708641 0.1078733 ]
 [0.07994404 0.27901793 0.29286343 0.1920851  0.53389002 0.4087916 ]
 [0.55227225 0.24601707 0.89556209 0.09686409 0.1970105  0.56539503]
 [0.56174236 0.3220829  0.88632236 0.04812905 0.59132507 0.20259943]]
Transposed matrix, [[0.80261215 0.98627718 0.94468356 0.07994404 0.55227225 0.56174236]
 [0.95291481 0.35064656 0.6652367  0.27901793 0.24601707 0.3220829 ]
 [0.06618431 0.96643981 0.08343675 0.29286343 0.89556209 0.88632236]
 [0.00711457 0.52098375 0.87144822 0.1920851  0.09686409 0.04812905]
 [0.04169387 0.25743676 0.27708641 0.53389002 0.1970105  0.59132507]
 [0.02797157 0.11908936 0.1078733  0.4087916  0.56539503 0.20259943]]
Thus the matricies are not equal.


In [40]:
print(transpose(transpose(A))-A,"= 0")

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] = 0


## Q1c

Write a function that finds the maximum entry in a matrix (where the matrix does not need to be square). Do this by writing loops and not using any special functions like `np.max` or any functions from any other library.

In [41]:
def maximum(A): #Using a power method approach as outlined in lectures. 
    Max = A[0][0]
    for i in range(0,A.shape[0]):
        for j in range(0,A.shape[1]):
            if(Max < A[i][j]):
                Max = A[i][j]
    return Max

Check your result by comparing to `np.max(A)` for the below random matrix

In [42]:
A = np.random.rand(4,5)

In [43]:
print("np.max(A) = ", np.max(A))

np.max(A) =  0.9969941785327485


In [44]:
print("Maximum(A) =", maximum(A))

Maximum(A) = 0.9969941785327485


# Question 2:  matrix norms

In the lectures we focused on the $L^2$-norm. We also briefly mentioned the $L^1$ and $L^\infty$ norm. Let's look at calculating those as well for a general $m\times n$ matrix.

# Q2a

The $L^1$ norm is given by

$$ \lVert A \rVert_1 = \max_j \sum^m_{i=1} |a_{ij}| $$

i.e., it is the max of the sums of the absolute values of each column. Write a function that computes the $L^1$-norm using only loops. The function should use no special numpy functions except `np.abs()`.

In [45]:
def L1(A):
    max1 = 0
    for j in range(0,A.shape[1]):
        sum1 = 0
        for i in range(0,A.shape[0]):
            sum1 += np.abs(A[i][j])
        if(max1 < sum1):
            max1 = sum1
    return max1

Check your result against NumPy's `la.norm(A,1)` function for the following random matrix

In [46]:
A = np.random.rand(3, 4)

In [47]:
print("la.norm(A,1) = ", la.norm(A,1))

la.norm(A,1) =  1.6600287138853842


In [48]:
print("L1(A) =", L1(A))

L1(A) = 1.6600287138853842


## Q2b

The $L^\infty$ norm is given by 

$$\lVert A \rVert_\infty = \max_i \sum_{j=1}^n |a_{ij}|$$

i.e., it is the max of the sums of the absolute values of each row. Write a function that computes the $L^\infty$-norm using only loops and no special numpy functions.

In [49]:
def Linf(A):
    msum = 0
    for i in range(0, A.shape[0]):
        sum1 = 0
        for j in range(0,A.shape[1]):
            sum1 += np.abs(A[i][j])
        if(msum < sum1):
            msum = sum1
    return msum

Check your result against NumPy's `la.norm(A,np.inf)` function for the following random matrix

In [50]:
A = np.random.rand(3, 4)

In [51]:
print("la.norm(A, np.inf) = ", la.norm(A, np.inf))

la.norm(A, np.inf) =  2.959644344435546


In [52]:
print("Linf(A) =", Linf(A))

Linf(A) = 2.959644344435546


# Question 3: ill-conditions systems of equations

In this question you can use any of NumPy's functions.

## Q3a

Which of the following three matrices, $A1, A2, A3$, are ill-conditioned. State the reason for your conclusion.

In [53]:
A1 = np.array([[0.988746460106, 0.351486109477, 0.024911477532, 0.384039749683],
       [0.282104657306, 0.239884151775, 0.36170151991 , 0.903082266861],
       [0.59333290915 , 0.637178863968, 0.241229214635, 0.685595037901],
       [0.013591747828, 0.917926970364, 0.458689093885, 0.157821121254]])

A2 = np.array([[ 2.852416473483e-01,  3.803483118694e-01,  2.697704226632e-01,  6.810611849029e-01],
       [ 6.622827828376e-01,  6.447943415836e-01,  4.387842058829e-01,  1.530575702376e+00],
       [ 3.672130860703e-01,  8.309522079704e-01,  9.975487474007e-01,  5.678296337101e-01],
       [ 4.036490000599e-01,  6.865978225967e-06,  8.788095913773e-01, -7.150472427928e-02]])

A3 = np.array([[0.131923621844, 0.245316154195, 0.732362341613, 0.957047891764],
       [0.91290446184 , 0.512312007959, 0.391938831444, 0.092509684772],
       [0.648708523652, 0.608576675797, 0.576773587276, 0.065385122929],
       [0.502955480393, 0.084082960221, 0.659487390444, 0.662958739412]])

In [54]:
print(la.cond(A1), "is A1's condition number thus we can conclude it's well conditioned.")
print(la.cond(A2), "is A2's condition number thus we can conclude it's well conditioned.")
print(la.cond(A3), "is A3's condition number thus we can conclude it's well conditioned.")

21.552466488381846 is A1's condition number thus we can conclude it's well conditioned.
13334936994.070848 is A2's condition number thus we can conclude it's well conditioned.
15.12244969941062 is A3's condition number thus we can conclude it's well conditioned.


# Q3b

With $b = [1,2,3,4]$ and $\delta b = [0.1,0,0,0]$ for $A2$ and $A3$ calculate the percentage change in $x$ due to a small change in $b$, i.e., calculate 

$$100\times\frac{\lVert \delta x_i\rVert_2}{\lVert x_i \rVert_2}\quad\text{and}\quad 100\times\frac{\lVert \delta b\rVert_2}{\lVert b \rVert_2}$$

where $(x_i+\delta x_i)  = A_i^{-1}(b+\delta b)$ and $i\in\{2,3\}$.

In [55]:
def L2(x):
    Sum = 0
    for i in x:
        Sum += i**2
    return(np.sqrt(Sum))

In [56]:
b = [1,2,3,4]
db = [0.1,0,0,0]

In [57]:
print("Change in b =", round(100*L2(db) / L2(b), 2), "%")

Change in b = 1.83 %


In [58]:
lA2b = L2(np.dot(la.inv(A2), b))
lA2db= L2(np.dot(la.inv(A2),db))

In [59]:
print("Change in x for A2 =", round(100*lA2db / lA2b,2), "%")

Change in x for A2 = 512.62 %


In [60]:
lA3b = L2(np.dot(la.inv(A3), b))
lA3db= L2(np.dot(la.inv(A3),db))

In [61]:
print("Change in x for A3 =", round(100*lA3db / lA3b,2), "%")

Change in x for A3 = 2.17 %


Which system of equations is more sensitive to small changes in $b$? How could you have guessed this from the answer to the Q3a?

In [62]:
# Answer here

#Due to it's large condition number, A2 has the highest sensitivity due to changes in b.
#This can be seen from comparison of the other condition numbers in Q3 (a)

# Question 4: eigensystems

In this question we look at finding eigenvalues and eigenvectors

## Q4a

You may use any of NumPy's functions for this sub-question.

Find the eigenvalues and eigenvectors for the below matrix. Print out the eigenvalues sorted by descending value and explicitly show that eigenvalues/eigenvector pairs satisfy $Ax = \lambda x$.

In [63]:
A = np.array([[1, 4, 5], [4, 5, 4], [6, 7, 9]])

In [64]:
(values,vectors) = la.eig(A)
print("The eigenvlaues are",round(values[0],3),",",round(values[2],3),"and",round(values[1],3))
for i in range(0,3):
    print("A * vectors["+str(i)+"] =",np.dot(A,vectors[:,i]),"=",round(values[i],2),"* vectors["+str(i)+"] =",np.dot(values[i],vectors[:,i]))

The eigenvlaues are 15.786 , 1.266 and -2.052
A * vectors[0] = [ -6.1962015   -7.01266016 -12.71289871] = 15.79 * vectors[0] = [ -6.1962015   -7.01266016 -12.71289871]
A * vectors[1] = [ 1.83806756 -0.74382849 -0.52676368] = -2.05 * vectors[1] = [ 1.83806756 -0.74382849 -0.52676368]
A * vectors[2] = [ 0.12430099 -0.98053324  0.79103825] = 1.27 * vectors[2] = [ 0.12430099 -0.98053324  0.79103825]


# Q4b

Without using NumPy's `la.eig()` (or similar functions), find the 4 eigenvalues and eigenvectors of the following matrix. Hint: Use the power method for the max eigenvalue (given below in `MaxEigenvalue`), the power method applied to the inverse for the smallest eigenvalue, and apply Hotelling's deflation twice to find the second and third eigenvalues/eigenvectors.

In [65]:
A = np.array([[1.935052353404, 0.887037260957, 1.534235483277, 1.370691224125],
       [0.887037260957, 0.81275989158 , 0.610238622918, 0.999150521052],
       [1.534235483277, 0.610238622918, 1.562260333538, 1.007843062517],
       [1.370691224125, 0.999150521052, 1.007843062517, 1.813258814483]])

In [67]:
def MaxEigenvalue(A, err):
    (m,n) = A.shape
    if(m != n):
        print("Matrix must be square")
        return
    x = np.random.rand(m)
    
    lam = 0.1
    lamprev = 1
    while np.abs(1-lam/lamprev) > err:
        p = np.dot(A,x)
        lamprev = lam
        lam = np.max(p)
        x = p/lam
        
    x = x/la.norm(x)
    return (lam,x)

In [68]:

def Areduce(matrix,value,vector):
    Areduce = np.empty(A.shape)
    uuT = np.empty([len(vector),len(vector)])
    for i in range(0,A.shape[0]):
        for j in range(0,A.shape[1]):
            uuT[i][j] = vector[i]*vector[j]
            Areduce[i][j] = matrix[i][j] - value*uuT[i][j]
    return Areduce

The eigenvalues are qeual to 4.915 0.851 0.215 0.143
The eigenvectors are equal to the columns of:
 [[ 0.59947643 -0.30724043  0.38116617  0.63319961]
 [ 0.33318804  0.38944484  0.67390096 -0.53214539]
 [ 0.49528115 -0.58292449 -0.34000252 -0.54707608]
 [ 0.53320758  0.64353327 -0.53382406  0.1287917 ]]


In [ ]:
values = np.zeros(4)
vectors = np.empty([4,4])

In [ ]:
(values[0],vectors[:,0]) = MaxEigenvalue(A,10**-6)
u1 = vectors[:,0]

In [ ]:
Areduce1 = Areduce(A,values[0],u1)
(values[1],vectors[:,1]) = MaxEigenvalue(Areduce1,10**-6)
u2 = vectors[:,1]

In [ ]:
Areduce2 = Areduce(Areduce1,values[1],u2)

(values[2],vectors[:,2]) = MaxEigenvalue(Areduce2,10**-6)
(values[3],vectors[:,3]) = (1/MaxEigenvalue(la.inv(A),10**-8)[0],MaxEigenvalue(la.inv(A),10**-8)[1])

In [70]:
print("The eigenvalues are equal to", round(values[0],3),round(values[1],3),round(values[2],3),round(values[3],3))
print("The eigenvectors are equal to the columns of:\n",vectors)

The eigenvalues are equal to 4.915 0.851 0.143 0.215
The eigenvectors are equal to the columns of:
 [[ 0.59947641  0.30724064 -0.63319959 -0.3811686 ]
 [ 0.33318806 -0.3894447   0.53214542 -0.67389895]
 [ 0.49528112  0.58292464  0.54707607  0.34000478]
 [ 0.53320761 -0.64353313 -0.12879172  0.53382343]]


Check your answers against Numpy's results from `la.eig(A)`

In [69]:
(values,vectors) = la.eig(A) 
print("The eigenvalues are qeual to",round(values[0],3),round(values[1],3),round(values[2],3),round(values[3],3))
print("The eigenvectors are equal to the columns of:\n",vectors)

The eigenvalues are qeual to 4.915 0.851 0.143 0.215
The eigenvectors are equal to the columns of:
 [[ 0.59947641  0.30724064 -0.63319959 -0.3811686 ]
 [ 0.33318806 -0.3894447   0.53214542 -0.67389895]
 [ 0.49528112  0.58292464  0.54707607  0.34000478]
 [ 0.53320761 -0.64353313 -0.12879172  0.53382343]]
